# This file is a template, and might need editing before it works on your project.
image: uogsoe/soe-php-apache:7.2-ci

# Services
services:
  - mysql:5.7

# Variables
variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:

  # Copy over testing configuration.
  # Don't forget to set the database config in .env.testing correctly
  - cp .env.gitlab .env
  - cp phpunit.xml.gitlab phpunit.xml

  # Install Composer and project dependencies.
  - composer install

  # Generate an application key.
  - php artisan key:generate
  - php artisan config:clear

  # Run database migrations.
  - php artisan migrate:fresh

test:
  script:
  # run laravel tests
  - php vendor/bin/phpunit --coverage-text --colors=never
